# Fehlerbehandlung
[10min]
Beispiel:
```python
def divide(a, b):
    return a / b
```

Es ist wichtig, Ausnahmen zu behandeln, um unerwartete Abst√ºrze zu vermeiden. 
Im Fall einer Division sollten wir insbesondere eine Division durch `0` abfangen. 
Beim Abfangen k√∂nnten wir den Code weiter laufen lassen:

```python
def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        print("Fehler: Division durch Null.")
        return None
```

oder wir lassen das programm abbrechen:

```python
import sys

def divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        print("Fehler: Division durch Null.")
        sys.exit(1)
```

Anderfalls wird die Exception als R√ºckgabe der Methode nach au√üen weitergeleitet und der Aufrufer von `divide` ist f√ºr
diese verantworlich. Entweder er f√§ngt sie selbt in einem Try-Catch block oder gibt sie weiter.

## Das `finally` Statement

[10 min]

Um die reibungslose und ordnungsgem√§√üe Abwicklung von Prozessen zu gew√§hrleisten, ist der Einsatz eines "finally"
Blocks oft empfehlenswert. In Python dient dieser Block dazu, bestimmte Aufr√§um- oder Abschlussarbeiten zu garantieren,
unabh√§ngig davon, ob w√§hrend der Ausf√ºhrung eine Ausnahme aufgetreten ist oder nicht.
Dies erweist sich als besonders vorteilhaft beim Umgang mit Ressourcen wie Dateien oder Netzwerkverbindungen,
da der "finally" Block sicherstellt, dass diese Ressourcen korrekt geschlossen oder freigegeben werden,
um das Entstehen von Ressourcenlecks zu verhindern.

```python
def datei_bearbeiten(dateipfad):
    try:
        datei = open(dateipfad, 'r')
        daten = datei.read()
        # Weiterverarbeitung der Daten
    except IOError:
        print("Fehler beim Lesen der Datei.")
    finally:
        # Dieser Block wird immer ausgef√ºhrt
        datei.close()
        print("Die Datei wurde geschlossen.")
    return daten

print(datei_bearbeiten("beispieldatei.txt"))
```

## Das "with" Statement
[10 min]

Das `with` Statement ist eine spezielle Form des `try` Statements, die es erm√∂glicht,
Ressourcen wie Dateien oder Netzwerkverbindungen zu √∂ffnen und zu schlie√üen.
Es ist eine gute Praxis, Ressourcen mit dem `with` Statement zu √∂ffnen, da es sicherstellt,
dass die Ressource nach der Verwendung geschlossen wird, selbst wenn w√§hrend der Ausf√ºhrung eine Ausnahme auftritt.

Die Methoden `__enter__` und `__exit__` in Klassen sind Teil des sogenannten Context Management 
Protocols in Python und werden vom `with`-Statement angestuert. Sie erm√∂glichen es einer Klasse, als Kontextmanager zu agieren, 
wodurch bestimmte Aktionen beim Betreten und Verlassen eines Kontexts automatisiert werden k√∂nnen. 
Diese Methoden sind besonders n√ºtzlich f√ºr Ressourcenmanagement, wie das sichere √ñffnen und Schlie√üen von Dateien 
oder Netzwerkverbindungen.

`__enter__(self):`
* Diese Methode wird aufgerufen, wenn der Ausf√ºhrungskontext durch das `with`-Statement betreten wird.
* Sie bereitet die Ressourcen vor oder f√ºhrt Initialisierungen durch, die f√ºr den Kontext erforderlich sind.
* Der R√ºckgabewert von `__enter__` wird an die Variable zugewiesen, die optional nach dem as im with-Statement steht.

`__exit__(self, exc_type, exc_value, traceback):`
* Diese Methode wird aufgerufen, wenn der Ausf√ºhrungskontext verlassen wird, das hei√üt am Ende des `with`-Blocks oder wenn innerhalb des Blocks eine Ausnahme auftritt.
* Sie ist verantwortlich f√ºr das Aufr√§umen oder Schlie√üen von Ressourcen.
* Die Parameter `exc_type`, `exc_value` und `traceback` enthalten Informationen √ºber eine etwaige Ausnahme, die im `with`-Block aufgetreten ist. Wenn der Block ohne Ausnahme verlassen wird, sind alle drei Werte None.

Anbei ein einfaches Beispiel f√ºr eine Klasse mit implementierten `__enter__` und `__exit__` Methoden:

```python
class MeinKontextManager:
    def __enter__(self):
        # Initialisierungen oder Ressourcen √∂ffnen
        return self  # oder ein anderes Objekt

    def __exit__(self, exc_type, exc_value, traceback):
        # Aufr√§umen oder Ressourcen schlie√üen
        # Kann True zur√ºckgeben, um eine Ausnahme zu unterdr√ºcken, sonst None
        ...
```

Dann k√∂nnen Methodeninstanzen im `with`-Block aufgerufen werden:

```python
with MeinKontextManager() as manager:
    # Aktionen innerhalb des Kontextes
    ...
```

### Aufgabe: Context Manager üå∂üå∂üå∂
Gegeben ist eine Beispielklasse `MeineRessource`, die das Context Management Protocol implementiert,
um sicherzustellen, dass Ressourcen ordnungsgem√§√ü ge√∂ffnet und geschlossen werden.
Ihre Aufgabe ist es, die Klasse so zu modifizieren, dass sie das `with`-Statement unterst√ºtzt,
um eine Ressource zu √∂ffnen und automatisch zu schlie√üen.

* Implementieren Sie die Methoden `__enter__` und `__exit__` in der Klasse MeineRessource.
* `__enter__` soll eine Nachricht ausgeben, die anzeigt, dass die Ressource ge√∂ffnet wird.
* `__exit__` soll eine Nachricht ausgeben, die anzeigt, dass die Ressource geschlossen wird und sie soll die Ressource schlie√üen.
* Verwenden Sie die Klasse in einem with-Block, um zu demonstrieren, dass sie wie beabsichtigt funktioniert.

```python
class MeineRessource:
    def oeffnen(self):
        print("Ressource ge√∂ffnet")

    def schliessen(self):
        print("Ressource geschlossen")

# Beispiel zur Verwendung der Klasse (dies soll modifiziert werden)
ressource = MeineRessource()
ressource.oeffnen()
# Code zur Nutzung der Ressource
ressource.schliessen()
```

[L√∂sung](solution.md)
